### ISSUE TITLE
[Help wanted] I can't open the program

### ISSUE THREAD

**Issue by oketariq** [TypicalHog/THCrypt#3]
I **downloaded** the program but it didn't open. What do i do? **:)**

**Comment by TypicalHog** [comment]
Have you tried dragging a file (a picture or a text file for example) onto the program?
Once you do that a file named key.txt will be created (you can also create it beforehand), open it and write the password inside, save it and drag your file onto the program once again. A new encrypted version of your file will be created and to decrypt it you will need to drag the encrypted file onto the program again. The password inside the key.txt file has to be the one that was used to encrypt the file.
Besides drag & drop you can also use the command line as explained in the readme file.

**Comment by oketariq** [comment]
Oh thanks you, but im not pretty interested in this program anymore, sorry
:(

2017-10-16 21:32 GMT+02:00 TypicalHog <notifications@github.com>:
